export enum AppEvents {
  QUIT='@@APP/QUIT'
}
export enum SystemInfoEvents {
  REQUEST='@@SYSTEM_INFO/REQUEST',
  RESPONSE='@@SYSTEM_INFO/REQUEST'
}

export enum DevToolsEvents {
  TOOGLE='@@DEV_TOOLS/TOOGLE'
}

export enum FileBrowserEvents {
  CHOOSE_DIR= '@@FILE_BROWSER/CHOOSE_DIR',
  PROJECT_PATH = '@@FILE_BROWSER/PROJECT_PATH'
}

export enum ReadWriteEvents {
  WRITE_FILE_NEW='@@READ_WRITE/WRITE_FILE_NEW',
  WRITE_FILE_CHANGES='@@READ_WRITE/WRITE_FILE_CHANGES',
  READ_FILE='@@READ_WRITE/READ_FILE',
  DELETE_FILE='@@READ_WRITE/DELETE_FILE'
}

export enum ProjectsEvents {
  REQUEST='@@PROJECTS/REQUEST',
  RESPONSE='@@PROJECTS/RESPONSE'
}
