export enum AppEvents {
  QUIT='@@APP/QUIT'
}
export enum SystemInfoEvents {
  REQUEST='@@SYSTEM_INFO/REQUEST',
  RESPONSE='@@SYSTEM_INFO/RESPONSE',
}

export enum DevToolsEvents {
  TOOGLE='@@DEV_TOOLS/TOOGLE'
}

export enum FileBrowserEvents {
  CHOOSE_DIR= '@@FILE_BROWSER/CHOOSE_DIR',
  PROJECT_PATH = '@@FILE_BROWSER/PROJECT_PATH',
  CHOOSE_FILE = '@@FILE_BROWSER/CHOOSE_FILE'
}

export enum ReadWriteEvents {
  WRITE_FILE_NEW='@@READ_WRITE/WRITE_FILE_NEW',
  WRITE_FILE_CHANGES='@@READ_WRITE/WRITE_FILE_CHANGES',
  WRITE_FILE_STATUS='@@READ_WRITE/WRITE_FILE_STATUS',
  READ_FILE='@@READ_WRITE/READ_FILE',
  READ_FILE_ERROR='@@READ_WRITE/READ_FILE_ERROR',
  DELETE_FILE='@@READ_WRITE/DELETE_FILE',
  DELETE_FILE_ERROR='@@READ_WRITE/DELETE_FILE_ERROR'

}

export enum ProjectsEvents {
  REQUEST='@@PROJECTS/REQUEST',
  RESPONSE='@@PROJECTS/RESPONSE',
  UPDATE='@@PROJECTS/UPDATE'
}
