/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Primeiros Passos',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/tutorial'
      ]
    },
    { Guides: [{ type: 'autogenerated', dirName: 'guides' }] },
    {
      type: 'category',
      label: 'Desenvolvimento',
      collapsed: false,
      items: [
        'developers-guide/setup-dev-env',
        'developers-guide/start-ribozilla'
      ]
    }
  ],
  apiSidebar: [
    { type: 'autogenerated', dirName: 'api' }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}
